### PR TITLE
Translate the store page 

### PR DESCRIPTION
**Pull request by omer358**

### CODE REVIEW

**Comment by ferraridamiano** [comment]
Hi @omer358 and thank you again for your work!
Can you remove everything other than full description, short description and title? There is no need to copy/paste all the other files because what is not translated is automatically copied

Thank you!

**Comment by omer358** [comment]
The translation instructions said I should copy/past & rename the entire folder 📂.
But, sure! Coming right way 👍

**Comment by ferraridamiano** [comment]
I'm sorry, you are right, the instructions are not very clear on this, I will fix them!

Thank you for this PR, now it is ready to be merged!

**Comment by omer358** [comment]
I'm the one who should be thanking you for making the opportunity ❤️
Last thing, I'm wondering when you are going publish the next release of the app?

**Comment by ferraridamiano** [comment]
It's nice to contribute to OSS, we all should do it more!

I do this little project in my free time. But I'm in the process of finishing my master degree and the free time is not that much. In the next release I plan to migrate to material you ([when the flutter team complete the work](https://github.com/flutter/flutter/projects/211)) and maybe adding more units.

But if you want to see your work in production I can deploy the changes in these days.

**Comment by omer358** [comment]
Good luck with your master ❤️ keep the good work up 🙌.
Yes, please, I would be thankful!

**Comment by ferraridamiano** [comment]
Thank you!
Sure, give me some days and I will publish it 😉

**Comment by ferraridamiano** [comment]
Done!

**Comment by omer358** [comment]
Thank you ❤️

**Pull request merged**
